### PR TITLE
Addaded Readme(Hactoberfest version)

### PR DESCRIPTION
**Pull request by GovindCodes**

### CODE REVIEW

**Comment by GovindCodes** [comment]
#1 Completed

**Comment by Devansh-Maurya** [comment]
Please correct the typo in the title, only if it hasn't been done to grab attention 😅

**Comment by GovindCodes** [comment]
Sir, that is how we will increase the reach 😄 🥇 😅

**Comment by Devansh-Maurya** [comment]
Wow, I totally missed the wrong spelling of Hacktoberfest. I just noticed the **Addaded** part, which is still as it is 😁

**Comment by GovindCodes** [comment]
Aahh, this time i missed the first part 😅.
Now its done 😀

**Pull request merged**
